c5
ERROR: Could not find a version that satisfies the requirement opencv-python-headless==4.2.0.32 (from -r /tmp/build_ffe07bd6/requirements.txt (line 18)) (from versions: 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.14.51, 3.4.14.53, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.2.52, 4.5.2.54)
       ERROR: No matching distribution found for opencv-python-headless==4.2.0.32

deploy conflict  5

solving deploy issue 4

solving deploy conflict 3

solving deploy conflict

deploy conflict solving